server:
  port: 8080
#  compression:
    # 开启响应压缩
#    enabled: true
#    mine-type:
#     - application/javascript
#     - text/css
#     - application/json
#     - application/xml
#     - text/html
#     - text/xml
#     - text/plain
#     - image/png
#    min-response-size: 2KB

spring:
  messages:
    basename: i18n/messages

  application:

    name: graphApplication

  datasource:
    url: jdbc:h2:file:./data
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: h2

  h2:
    console:
      enabled: true
  graphql:
    websocket:
      path: /graphql
    path: /graphql
    graphiql:
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=3s
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板

logging:
  level:
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bin: TRACE

